import { access, cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, "..");
const outputDirectory = resolve(projectRoot, "dist");

/** 로컬 개발용 .env가 있으면 단순 KEY=VALUE 형식으로 읽습니다. Render에서는 시스템 환경변수가 우선합니다. */
async function loadLocalEnvironment() {
  const envPath = resolve(projectRoot, ".env");
  try {
    await access(envPath, constants.R_OK);
    const contents = await readFile(envPath, "utf8");
    for (const line of contents.split(/\r?\n/)) {
      const trimmedLine = line.trim();
      if (!trimmedLine || trimmedLine.startsWith("#")) continue;
      const separatorIndex = trimmedLine.indexOf("=");
      if (separatorIndex < 1) continue;
      const key = trimmedLine.slice(0, separatorIndex).trim();
      const value = trimmedLine.slice(separatorIndex + 1).trim().replace(/^['"]|['"]$/g, "");
      if (!process.env[key]) process.env[key] = value;
    }
  } catch {
    // .env 파일은 선택 사항이며 Render에서는 대시보드 환경변수를 사용합니다.
  }
}

await loadLocalEnvironment();

const requiredVariables = ["SUPABASE_URL", "SUPABASE_PUBLISHABLE_KEY"];
const missingVariables = requiredVariables.filter((name) => !process.env[name]);
if (missingVariables.length > 0) {
  throw new Error(`Missing required environment variables: ${missingVariables.join(", ")}`);
}

const publicFiles = [
  "index.html",
  "styles.css",
  "app.js",
  "supabase-service.js",
  "weather-service.js",
];

await rm(outputDirectory, { recursive: true, force: true });
await mkdir(outputDirectory, { recursive: true });

for (const file of publicFiles) {
  await cp(resolve(projectRoot, file), resolve(outputDirectory, file));
}

// JSON.stringify를 사용해 환경변수 안의 따옴표나 줄바꿈이 JavaScript를 깨뜨리지 않게 합니다.
const browserConfig = `// Generated during the Render build. Do not edit this file directly.\nwindow.GREENON_CONFIG = ${JSON.stringify(
  {
    supabaseUrl: process.env.SUPABASE_URL,
    supabasePublishableKey: process.env.SUPABASE_PUBLISHABLE_KEY,
    weatherApiUrl: process.env.WEATHER_API_URL || "",
  },
  null,
  2,
)};\n`;

await writeFile(resolve(outputDirectory, "supabase-config.js"), browserConfig, "utf8");
console.log(`Carrier GreenON static build created at ${outputDirectory}`);
